import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import contactsRouter from "./contacts";
import companiesRouter from "./companies";
import leadsRouter from "./leads";
import dealsRouter from "./deals";
import activitiesRouter from "./activities";
import invoicesRouter from "./invoices";
import productsRouter from "./products";
import quotesRouter from "./quotes";
import openrouterRouter from "./openrouter/index";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";
import webhooksRouter from "./webhooks";
import whatsappRouter from "./whatsapp";
import whatsappGuardrailsRouter from "./whatsapp_guardrails";
import whatsappFlowsRouter from "./whatsapp_flows";
import whatsappSessionRouter from "./whatsapp_session";
import portalRouter from "./portal";
import afipRouter from "./afip";
import appointmentsRouter from "./appointments";
import ordersRouter from "./orders";
import broadcastRouter from "./broadcast";
import paymentsRouter from "./payments";
import servicesRouter from "./services";
import prospectorRouter from "./prospector";
import analyticsRouter from "./analytics";
import newsletterRouter from "./newsletter";
import woocommerceRouter from "./woocommerce";
import copilotRouter from "./copilot";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(settingsRouter);
router.use(contactsRouter);
router.use(companiesRouter);
router.use(leadsRouter);
router.use(dealsRouter);
router.use(activitiesRouter);
router.use(invoicesRouter);
router.use(productsRouter);
router.use(quotesRouter);
router.use(openrouterRouter);
router.use(dashboardRouter);
router.use(webhooksRouter);
router.use(whatsappRouter);
router.use(whatsappGuardrailsRouter);
router.use(whatsappFlowsRouter);
router.use(whatsappSessionRouter);
router.use(portalRouter);
router.use(afipRouter);
router.use(appointmentsRouter);
router.use(ordersRouter);
router.use(broadcastRouter);
router.use(paymentsRouter);
router.use(servicesRouter);
router.use(prospectorRouter);
router.use(analyticsRouter);
router.use(newsletterRouter);
router.use(woocommerceRouter);
router.use(copilotRouter);

export default router;
