// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/V1.tsx": () => import("../components/mockups/landing/V1.tsx"),
  "./components/mockups/landing/V2.tsx": () => import("../components/mockups/landing/V2.tsx"),
  "./components/mockups/landing/VariantA.tsx": () => import("../components/mockups/landing/VariantA.tsx"),
  "./components/mockups/landing/VariantB.tsx": () => import("../components/mockups/landing/VariantB.tsx"),
  "./components/mockups/login/Refined.tsx": () => import("../components/mockups/login/Refined.tsx"),
  "./components/mockups/login/SplitLayout.tsx": () => import("../components/mockups/login/SplitLayout.tsx"),
  "./components/mockups/login/VariantA.tsx": () => import("../components/mockups/login/VariantA.tsx"),
  "./components/mockups/login/VariantB.tsx": () => import("../components/mockups/login/VariantB.tsx")
};
