// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clientum-landing/Current.tsx": () => import("../components/mockups/clientum-landing/Current.tsx"),
  "./components/mockups/clientum-landing/RefinedA.tsx": () => import("../components/mockups/clientum-landing/RefinedA.tsx"),
  "./components/mockups/clientum-landing/RefinedB.tsx": () => import("../components/mockups/clientum-landing/RefinedB.tsx")
};
